Metaanalysis: pooled log(RR)

```{r}
pooled_logRR <- get_logRR_pooled(d_ERR_wide_ma)

if(!inherits(pooled_logRR, "try-error")) {
    pooled_logRR_out <- pooled_logRR
    
    ## add weigths
    ## consider that there may be fewer weights than
    ## rows due to studies with missings that are not pooled
    ma_weights       <- weights(pooled_logRR)
    d_ma_weights     <- data.frame(auth_year=names(ma_weights),
                                   weight=unname(ma_weights))
    
    names_org <- stringr::str_remove(names(ma_weights), "\\.[[:digit:]]{1}")
    ma_weights_ok <- (length(ma_weights) == nrow(d_ERR_wide_ma)) &&
                     all(names_org       == d_ERR_wide_ma$auth_year)
    
    if((cancer_site == "all_solid") && (ma_weights_ok)) {
        d_ERR_out <- d_ERR_wide_ma %>%
            mutate(site=cancer_site,
                   weight=unname(weights(pooled_logRR))) %>%
            select(site, auth_year, Study, ERR, ERR_CIlo, ERR_CIup, ERR_SE_meta, weight, used) %>%
            rename(ERR_SE=ERR_SE_meta)
    } else {
        d_ERR_out <- d_ERR_wide_ma %>%
            mutate(site=cancer_site) %>%
            left_join(d_ma_weights, by="auth_year") %>%
            select(site, auth_year, Study, ERR, ERR_CIlo, ERR_CIup, ERR_SE_meta, weight, used) %>%
            rename(ERR_SE=ERR_SE_meta)
    }
} else {
    pooled_logRR_out <- data.frame(tau2=NA_real_,
                                   se.tau2=NA_real_,
                                   I2=NA_real_,
                                   H2=NA_real_,
                                   QE=NA_real_,
                                   QEp=NA_real_)

    d_ERR_out <- data.frame(site=cancer_site,
                            auth_year=NA_character_,
                            Study=NA_character_,
                            ERR=NA_real_,
                            ERR_CIlo=NA_real_,
                            ERR_CIup=NA_real_,
                            ERR_SE_meta=NA_real_,
                            weight=NA_real_,
                            used="none")
}

# if(meta_type != "special") {
    d_ERR_out %>% select(-site, -Study)
# }

pooled_logRR_out
```

Metaanalysis: Pooled ERR = exp(logRR) - 1

```{r}
ci_pred <- if(!inherits(pooled_logRR, "try-error")) {
    predict(pooled_logRR, transf=transf_logRR_to_ERR, pi.type="riley")
} else {
    data.frame(pred=NA_real_,
               ci.lb=NA_real_,
               ci.ub=NA_real_,
               pi.lb=NA_real_,
               pi.ub=NA_real_)
}

ci_pred
```

```{r}
## save results for combined table / figure
## input ERR only from primary analysis
if(meta_type == "primary") {
    assign(paste0("d_ERR_site_", cancer_site), d_ERR_out)
}

assign(paste0("d_meta_", cancer_site, "_", meta_type),
       data.frame(site=cancer_site,
                  type=meta_type,
                  tau2=pooled_logRR_out$tau2,
                  # tau2_se=pooled_logRR_out$se.tau2,
                  I2=pooled_logRR_out$I2,
                  H2=pooled_logRR_out$H2,
                  Q=pooled_logRR_out$QE,
                  Q_pval=pooled_logRR_out$QEp,
                  ERR=ci_pred$pred,
                  ERR_CIlo=ci_pred$ci.lb,
                  ERR_CIup=ci_pred$ci.ub,
                  ERR_PIlo=ci_pred$pi.lb,
                  ERR_PIup=ci_pred$pi.ub))
```
